### ISSUE TITLE
is this a grabber?

### ISSUE THREAD

**Issue by ody007gr** [Umbra999/VRC-EOSDisabler#1]
if it is, fuck you

**Comment by Umbra999** [comment]
dude its open source? just look at the damn code???

**Comment by ody007gr** [comment]
I did look at the code, idk maybe you uploaded a different file to the builds

**Comment by Umbra999** [comment]
dude then just compile it yourself if u dont trust the compiled binary? thats what github is made for?

**Comment by ody007gr** [comment]
Btw does it still work?, I ran the file and nothing happend, just flashed me with cmds, do I need to have vrchat open?
